
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            DataTables Catalog Tables
            <a href="/multiple/admin/category/new" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> New</a>
            <a href="/multiple/admin/category/deleteAll" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Delete All</a>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <?php
            if($this->flashSession->output()){
                ?>
                <div class="alert alert-success"><?php echo $this->flashSession->output(); ?></div>
                <?php
            }
            ?>
            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                <tr>
                    <th><input type="checkbox" name="checkall[]"></th>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Parent_ID</th>
                    <th>Create_time</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($page->items as $cat):


                    ?>
                    <tr class="odd gradeX">
                        <td><input type="checkbox" name="check[]" value="<?php //echo $cat->id; ?>"></td>
                        <td><?php //echo $cat->id; ?></td>
                        <td><?php //echo $cat->name; ?></td>
                        <td><?php //echo $cat->parent_id; ?></td>
                        <td class="center"><?php //echo $cat->create_time; ?></td>
                        <td class="center">
                            <a href="/multiple/admin/category/edit?id=<?php //echo $cat->id ?>" style="color: blue" data-toggle="tooltip" title="Edit" class="glyphicon glyphicon-edit">Edit</a>
                            <a href="/multiple/admin/category/delete?id=<?php //echo $cat->id ?>" style="color: red" data-toggle="tooltip" title="Delete" class="glyphicon glyphicon-trash">Delete</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <!-- /.table-responsive -->
            <nav aria-label="...">
                <ul class="pager">
                    <li <?php echo ($page->current == 1) ? 'class="disabled"' : ''; ?>><a href="/multiple/admin/category/index?page=1">First</a></li>
                    <li <?php echo ($page->current == 1) ? 'class="disabled"' : ''; ?>><a href="/multiple/admin/category/index?page=<?= $page->before; ?>">Previous</a></li>
                    <?php echo "You are in page ", $page->current, " of ", $page->total_pages; ?>
                    <li <?php echo ($page->current == $page->total_pages) ? 'class="disabled"' : ''; ?>><a href="/multiple/admin/category/index?page=<?= $page->next; ?>">Next</a></li>
                    <li <?php echo ($page->current == $page->total_pages) ? 'class="disabled"' : ''; ?>><a href="/multiple/admin/category/index?page=<?= $page->last; ?>">Last</a></li>
                </ul>
            </nav>


        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>





