<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Create Items Form <a href="/multiple/admin/category/" class="btn btn-success"><span class="fa fa-reply"></span> Undo</a>
        </div>
        <div class="panel-body">
            <form role="form" method="post">
            <div class="row">
                <?php
                    if($this->flash->output()){
                    ?>
                        <div class="alert alert-danger"><?php echo $this->flash->output(); ?></div>
                <?php
                    }
                ?>

                <div class="col-lg-6">
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control" name="name" placeholder="Name Food" value="">
                        <p class="help-block">Create Name Items</p>
                    </div>
                    <div class="form-group">
                        <label>Status</label>
                        <select class="form-control" name="status" id="">
                            <option selected value="">-- Choose Status--</option>
                            <option value="0">0</option>
                            <option value="1">1</option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>Price</label>
                        <input type="number" class="form-control" name="price" placeholder="Price" value="">
                        <p class="help-block">Create Name Items</p>
                    </div>
                    <div class="form-group">
                        <label>Desciprtion</label>
                        <input type="text" class="form-control" name="description" placeholder="Description" value="">
                        <p class="help-block">Create Description Items</p>
                    </div>
                    <div class="form-group">
                        <label>Number</label>
                        <input type="number" class="form-control" name="number" placeholder="Number">
                    </div>

                </div>
                <div class="col-lg-12">
                    <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-warning">Reset</button>
                </div>
            </div>
            </form>
            <!-- /.row (nested) -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>




