<!DOCTYPE html>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
    <meta charset="UTF-8">
    <title>Cinema Theater Website Template</title>
    <link rel="stylesheet" href="<?php echo PUBLIC_PATH; ?>/css/style.css" type="text/css">
    <link rel="stylesheet" href="<?php echo PUBLIC_PATH; ?>/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo PUBLIC_PATH; ?>/vendor/">
    <link href="/multiple/public/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <style>
        p{
            color:#fff;

        }
        h2,h3,h4,h5,h6{
            color:#C66B16; white-space:nowrap; overflow: hidden; text-overflow: ellipsis;
        }
        span{
            color:#cb2027;
        }
    </style>
</head>
<body>
<div id="header">
    <?php require_once 'header.phtml';   ?>
</div>
<div class="container">
    <?php echo $this->getContent(); ?>
</div>
<div id="footer">
<?php require_once 'footer.phtml'; ?>
</div>
<script src="/multiple/public/vendor/jquery/jquery.min.js"></script>
</body>
</html>