<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title></title>

    <?php require_once 'header.phtml'?>

</head>

<body>

<div id="wrapper">

    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <?php require_once 'menu.phtml'?>
    </nav>

    <div id="page-wrapper">
        <?php echo $this->getContent() ?>
<!--        dẫn tới thư mục layouts/-->
    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="/multiple/public/vendor/jquery/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/multiple/public/vendor/bootstrap/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="/multiple/public/vendor/metisMenu/metisMenu.min.js"></script>

<!-- Morris Charts JavaScript -->
<script src="/multiple/public/vendor/raphael/raphael.min.js"></script>
<script src="/multiple/public/vendor/morrisjs/morris.min.js"></script>
<script src="/multiple/public/data/morris-data.js"></script>
<link href="/multiple/public/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<!-- Custom Theme JavaScript -->
<script src="/multiple/public/dist/js/sb-admin-2.js"></script>
<script src="/multiple/public/vendor/jquery/date.js"></script>
</body>

</html>
