<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Create Items Form <a href="/multiple/admin/category/" class="btn btn-success"><span class="fa fa-reply"></span> Undo</a>
        </div>
        <div class="panel-body">
            <form role="form" method="post">
            <div class="row">
                <?php
                if($this->flash->output()){
                    ?>
                    <div class="alert alert-danger"><?php echo $this->flash->output(); ?></div>
                    <?php
                }
                ?>

                <div class="col-lg-6">

                        <div class="form-group">
                            <label>UserName</label>
                            <input required type="text" class="form-control" name="username" placeholder="Username" value="">
                            <p class="help-block">Create Name Items</p>
                        </div>
                        <div class="form-group">
                            <label>PassWord</label>
                            <input required type="password" class="form-control" name="password" placeholder="Password" value="">
                            <p class="help-block">Create Description Items</p>
                        </div>
                        <div class="form-group">
                            <label>FullName</label>
                            <input required type="text" class="form-control" name="fullname" placeholder="Fullname" value="">
                            <p class="help-block">Create Description Items</p>
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input required type="email" class="form-control" name="email" placeholder="Email" value="">
                            <p class="help-block">Create Description Items</p>
                        </div>

                </div>
                <div class="col-lg-6">

                    <div class="form-group">
                        <label>Identity_Card</label>
                        <input required type="text" class="form-control" maxlength="9" name="idc" placeholder="CMND" value="">
                        <p class="help-block">Create Name Items</p>
                    </div>
                    <div class="form-group">
                        <label>Phone</label>
                        <input required type="text" class="form-control" maxlength="11" name="phone" placeholder="Phone" value="">
                        <p class="help-block">Create Description Items</p>
                    </div>
                    <div class="form-group">
                        <label>Birthday</label>
                        <div>
                        <select required name="day" class="form-control" style="width: 30%; float: left" id="days"></select>
                        <select required name="month" class="form-control" style="width: 30%; float: left" id="months"></select>
                        <select required name="year" class="form-control" style="width: 30%;" id="years"></select>
                        </div>
                        <p class="help-block">Create Description Items</p>
                    </div>
                    <div class="form-group">
                        <label>Level</label>
                        <input required type="text" class="form-control" name="level" placeholder="Level But anyone Admin level 1 can choose" value="">
                        <p class="help-block">Create Description Items</p>
                    </div>

                </div>
                <div class="col-lf-12">
                    <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-warning">Reset</button>

                </div>
            </div>
            </form>
            <!-- /.row (nested) -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>




