<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Create Items Form <a href="/multiple/admin/category/" class="btn btn-success"><span class="fa fa-reply"></span> Undo</a>
        </div>
        <div class="panel-body">
            <div class="row">
                <?php
                    if($this->flash->output()){
                    ?>
                        <div class="alert alert-danger"><?php echo $this->flash->output(); ?></div>
                <?php
                    }
                ?>

                <div class="col-lg-6">
                    <form role="form" method="post">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" name="name" placeholder="Name Catalog" value="">
                            <p class="help-block">Create Name Items</p>
                        </div>
                        <div class="form-group">
                            <label>Desciprtion</label>
                            <input type="text" class="form-control" name="description" placeholder="Description Catalog" value="">
                            <p class="help-block">Create Description Items</p>
                        </div>
                        <div class="form-group">
                            <label>Parent_id</label>
                            <select class="form-control" name="parent_id" id="">
                                <option selected value="">-- Choose Parent_ID--</option>
                                <option value="0">0</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                            </select>
                        </div>
                        <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-warning">Reset</button>
                    </form>
                </div>

            </div>
            <!-- /.row (nested) -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>




