<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Create Items Form <a href="/multiple/admin/user/" class="btn btn-success"><span class="fa fa-reply"></span> Undo</a>
        </div>
        <div class="panel-body">
            <form role="form" method="post" enctype="multipart/form-data">
                <div class="row">
                    <?php
                    if($this->flashSession->output()){
                        ?>
                        <div class="alert alert-danger"><?php //echo $this->flashSession->output(); ?></div>
                        <?php
                    }
                    ?>
                    <?php
//                        echo '<pre>';
//                        print_r($user);
                    foreach($user as $value) {
                    ?>
                    <div class="col-lg-6">

                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" name="fullname" placeholder="Name Movie"
                                   value="<?php echo $value->fullname; ?>" maxlength="100" required>
                        </div>

                        <div class="form-group">
                            <label>Category_id</label>
                            <input type="text" class="form-control" name="phone" placeholder="Name Movie"
                                   value="<?php echo $value->phone; ?>" maxlength="100" required>
                        </div>
                        <div class="form-group">
                            <label>Price/Ticket</label><br>
                            <input name="email" class="form-control" value="<?php echo $value->email;  ?>" placeholder="Create Price The Movie" type="text" required>
                        </div>
                        <div class="form-group">
                            <label>Adult</label><br>
                            <input name="username" class="form-control" value="<?php echo $value->username;  ?>" placeholder="Create Price The Movie" type="text" required>
                        </div>
                        <div class="form-group">
                            <label>Image</label><br>
                            <input name="password" width="100" height="100" class="form-control" value="<?php echo $value->password ?>" type="text">



                        </div>
                        <div class="form-group">
                            <label>Description</label><br>
                            <textarea align="left" required name="address" maxlength="500" class="form-control" id="" cols="40" rows="">
                                <?php echo $value->address; ?>
                            </textarea>
                        </div>


                    </div>
                    <div class="col-lg-6">

                        <div class="form-group">
                            <label>Premiere</label>
                            <input type="date" placeholder="Determined for Movie" class="form-control" name="birthday" value="<?php echo $value->birthday; ?>" required>
                        </div>

                        <div class="form-group">
                            <label>Close_date_movie</label>
                            <input type="date" placeholder="Close for Movie" class="form-control" name="create_time" value="<?php echo $value->create_time; ?>" required>
                        </div>

                        <div class="form-group">
                            <label>Director</label>
                            <input type="text" placeholder="Who are Director ???" class="form-control" name="number_code" value="<?php echo $value->number_code; ?>" required>
                        </div>
                        <div class="form-group">
                            <label>Type_Movie</label>
                            <input type="text" placeholder="Who type Movie ???" class="form-control" name="number_star" value="<?php echo $value->number_star; ?>" required>
                        </div>
                        <div class="form-group">
                            <label>Time</label>
                            <input type="text" placeholder="How long the Movie ???" class="form-control" name="identity_card" value="<?php echo $value->identity_card;; ?>" required>
                        </div>
                        <div class="form-group">
                            <label>Actor</label>
                            <input type="text" placeholder="How long the Movie ???" class="form-control" name="level"  value="<?php echo $value->level; ?>">

                        </div>
                    </div>
                    <?php } ?>
                    <div class="col-lg-12">
                        <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                        <button type="submit" name="submit" class="btn btn-info">Go to Show time</button>
                        <button type="reset" class="btn btn-warning">Reset</button>
                    </div>


                </div>
            </form>
            <!-- /.row (nested) -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>




